// Generated by LiveScript 1.3.1
var startNim;
startNim = function(stageId){
  var rand01, stage, Coin, coinsInColumn, widthContext, heightContext, radContext, cfg, colRange, res$, i$, to$, ridx$, rowRange, makeCoin, makeColumn, addColumn, draw;
  rand01 = function(){
    return Math.random();
  };
  stage = new Stage(stageId);
  Coin = new BitmapData('Coin2.png');
  coinsInColumn = [];
  widthContext = window.innerWidth / 600;
  heightContext = window.innerHeight / 900;
  radContext = heightContext >= widthContext ? widthContext : heightContext;
  cfg = {
    maxCols: 6,
    maxRows: 8
  };
  res$ = [];
  for (i$ = 1, to$ = cfg.maxCols; i$ <= to$; ++i$) {
    ridx$ = i$;
    res$.push(ridx$);
  }
  colRange = res$;
  res$ = [];
  for (i$ = 1, to$ = cfg.maxRows; i$ <= to$; ++i$) {
    ridx$ = i$;
    res$.push(ridx$);
  }
  rowRange = res$;
  makeCoin = function(col, row){
    var coin;
    coin = new Bitmap(Coin);
    coin.x = widthContext * (100 * col - 90);
    coin.y = heightContext * (100 * row - 90);
    coin.col = col;
    coin.row = row;
    coin.scaleX = coin.scaleY = radContext * 0.8;
    coin.buttonMode = true;
    coin.alpha = 1;
    return coin;
  };
  makeColumn = function(col){
    return rowRange.map(function(row){
      return makeCoin(col, row);
    });
  };
  addColumn = function(col){
    var newColumn, r;
    newColumn = coinsInColumn[col] = makeColumn(col);
    r = rand01();
    return rowRange.filter(function(row){
      return r >= (row - 1) / cfg.maxRows;
    }).map(function(row){
      var coin;
      coin = newColumn[row - 1];
      console.log("adding coin at (" + col + "," + row + ")");
      stage.addChild(coin);
      return coin.addEventListener(MouseEvent.MOUSE_DOWN, function(event){
        var coin, i$, ref$, len$, c;
        coin = event.target;
        if (coin && coin.col) {
          console.log("You clicked on (" + coin.col + "," + coin.row + ")");
          for (i$ = 0, len$ = (ref$ = coinsInColumn[coin.col]).length; i$ < len$; ++i$) {
            c = ref$[i$];
            if (c.row >= coin.row) {
              console.log("removing (" + c.col + "," + c.row + ")");
              c.visible = false;
            }
          }
        }
      });
    });
  };
  draw = function(){
    colRange.map(addColumn);
  };
  draw();
};