// Generated by LiveScript 1.3.1
var startNim;
startNim = function(stageId){
  var rand01, stage, Coin, widthContext, heightContext, radContext, cfg, makeCoin, makeColumn, addColumn, draw;
  rand01 = function(){
    return Math.random();
  };
  stage = new Stage(stageId);
  Coin = new BitmapData('Coin2.png');
  widthContext = window.innerWidth / 600;
  heightContext = window.innerHeight / 900;
  radContext = heightContext >= widthContext ? widthContext : heightContext;
  cfg = {
    maxCols: 6,
    maxRows: 8
  };
  makeCoin = function(col, row){
    var coin;
    coin = new Bitmap(Coin);
    coin.x = widthContext * (100 * col - 90);
    coin.y = heightContext * (100 * row - 90);
    coin.col = col;
    coin.row = row;
    coin.scaleX = coin.scaleY = radContext * 0.8;
    coin.buttonMode = true;
    coin.alpha = 1;
    return coin;
  };
  makeColumn = function(col){
    return (function(){
      var i$, to$, results$ = [];
      for (i$ = 1, to$ = cfg.maxRows; i$ <= to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    }()).map(function(row){
      return makeCoin(col, row);
    });
  };
  addColumn = function(col){
    var coinsInColumn, r;
    coinsInColumn = makeColumn(col);
    r = rand01();
    return (function(){
      var i$, to$, results$ = [];
      for (i$ = 0, to$ = cfg.maxRows - 1; i$ <= to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    }()).filter(function(row){
      return r >= row / cfg.maxRows;
    }).map(function(row){
      var coin;
      coin = coinsInColumn[row];
      console.log("adding coin at (" + col + "," + row + ")");
      stage.addChild(coin);
      return coin.addEventListener(MouseEvent.MOUSE_DOWN, function(event){
        return event.target.visible = false;
      });
    });
  };
  draw = function(){
    (function(){
      var i$, to$, results$ = [];
      for (i$ = 1, to$ = cfg.maxCols; i$ <= to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    }()).map(addColumn);
  };
  draw();
};